name: Build ALCI Runit ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    container:
      image: artixlinux/runit:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV

      - name: Update packages
        run: pacman -Syu --noconfirm git squashfs-tools

      - name: Build ISO
        run: bash build.sh
        
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.DATE }}
          prerelease: false
          title: "ALCI-Runit"
          files: |
            ./artools-workspace/iso/base/
            
